name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2: Installation des dépendances
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 3: Exécution des tests unitaires
      - name: Run unit tests
        run: |
          pytest --maxfail=1 --disable-warnings
        env:
          ENV: test

      # Étape 4: Copier uniquement `app.py` sur PythonAnywhere
      - name: Copy app.py to PythonAnywhere
        run: |
          scp app.py muselion@Muselion.pythonanywhere.com:/home/muselion/mysite/app.py

      # Étape 4: Déploiement (si les tests passent)
      - name: Deploy to PythonAnywhere
        run: |
          ssh muselion@Muselion.pythonanywhere.com "touch /home/muselion/mysite/app.py && restart your_project"
